boy_name = input("Enter a boy name: ")
dinosaur = input("Enter a type of dinosaur: ")
noise = input("Enter a type of noise: ")
animal = input("Enter a type of animal: ")
body_part = input("Enter a type of body_part: ")
color = input("Enter a type of color: ")
something_stinky = input("Enter a type of smell: ")
number = input("Enter a number: ")
game = input("Enter a type of game: ")
emotion = input("Enter a type of emotion: ")

print(f"{boy_name} was a mighty {dinosaur}")
print(f"He would stomp around the jungle with a loud {noise}!")
print(f"The other dinosaurs thought he was good at hunting {animal} and had a very scary {body_part}")
print(f"He lived in a {color} cave that smelled like {something_stinky}")
print(f"He had {number} friends that always played {game} with him")
print(f"He was a very {emotion} dinosaur!")